package cine;

import java.util.*;
import javax.swing.JOptionPane;

public class REGISTRO_USUARIO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(REGISTRO_USUARIO.class.getName());

    /**
     * Creates new form REGISTRO_USUARIO
     */
    public REGISTRO_USUARIO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtnombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnprocesar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtnombres);
        txtnombres.setBounds(10, 62, 220, 30);

        jLabel3.setText("Nombres  y Apellidos ");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(10, 40, 116, 20);

        txtdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtdoc);
        txtdoc.setBounds(10, 132, 220, 30);

        jLabel4.setText("Doc De  identidad ");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(10, 110, 97, 16);
        jLayeredPane1.add(txtnum);
        txtnum.setBounds(10, 200, 220, 30);

        jLabel5.setText("Número de documento");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(10, 180, 170, 16);
        jLayeredPane1.add(txtedad);
        txtedad.setBounds(10, 270, 220, 30);

        jLabel6.setText("Edad ");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(10, 250, 66, 16);

        btnprocesar.setBackground(new java.awt.Color(51, 51, 255));
        btnprocesar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprocesar.setForeground(new java.awt.Color(255, 255, 255));
        btnprocesar.setText("REGISTRAR");
        btnprocesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocesarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnprocesar);
        btnprocesar.setBounds(10, 320, 220, 30);

        btnlimpiar.setBackground(new java.awt.Color(0, 255, 0));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnlimpiar);
        btnlimpiar.setBounds(10, 360, 220, 30);

        btnsalir.setBackground(new java.awt.Color(51, 51, 51));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnsalir);
        btnsalir.setBounds(10, 400, 220, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO  DE REGISTRO ");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 210, 26);

        jLayeredPane2.add(jLayeredPane1);
        jLayeredPane1.setBounds(10, 20, 230, 450);

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 250, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login_form_2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed

    }//GEN-LAST:event_txtnombresActionPerformed

    private void txtdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnprocesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocesarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Datos guardados satisfactoriamente");
    }//GEN-LAST:event_btnprocesarActionPerformed

    public void Limpiar(){
        this.txtnombres.setText("");
        this.txtdoc.setText("");
        this.txtedad.setText("");
        this.txtnum.setText("");
        
        this.txtnombres.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new REGISTRO_USUARIO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnprocesar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
